### PR TITLE
Add email and string length in range validators

### PR DESCRIPTION
**Pull request by MrEhbr**

### CODE REVIEW

**Comment by markbates** [comment]
Awesome! Thanks.

**Comment by MrEhbr** [comment]
Could you sign up in https://travis-ci.org for automatic tests?
When I will have free time i write some benchmark tests)

**Comment by markbates** [comment]
all set! :)

**Comment by MrEhbr** [comment]
Sory don't see, but it currently don't have builds(

**Comment by markbates** [comment]
It's turned on, but nothing has been built yet. Travis needs something to kick it.

**Pull request merged**
